# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

#    working_directory: ~/repo

    steps:
      - checkout
      - run echo $SONAR_TOKEN
      - run: openssl aes-256-cbc -d -in circle_certbundle.enc.zip -out circle_certbundle.zip -k $Decrypt_var
      - run: unzip circle_certbundle.zip
      - run: sudo apt-get update && sudo apt-get install openvpn
      - run: sudo openvpn --config ovpnclient.conf --remap-usr1 SIGTERM --connect-retry-max 2 --single-session -vv > r.txt &
      - run: sleep 10
      - run: ifconfig
      - run: cat r.txt
      #- run: wget -nv https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip
      #- run: unzip -quo sonar-scanner-cli-3.0.3.778-linux.zip -d ../
      #- run: sudo echo "sonar.host.url=http://10.172.0.1:9000" > ../sonar-scanner-3.0.3.778-linux/conf/sonar-scanner.properties
      #- run: ../sonar-scanner-3.0.3.778-linux/bin/sonar-scanner -Dsonar.login=$SONAR_TOKEN
      
      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-

#      - run: composer install -n --prefer-dist

#      - save_cache:
#          paths:
#            - ./vendor
#          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
#      - run: phpunit
