# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

#    working_directory: ~/repo

    steps:
      - checkout
      - run: openssl aes-256-cbc -d -in ssh_key_enc -out id_rsa -k $Decrypt_var
      - run: chmod 600 id_rsa
      - run: openssl aes-256-cbc -d -in circle_known_hosts -out known_hosts -k $Decrypt_var
      - run: rm ~/.ssh/known_hosts
      - run: mv ./known_hosts ~/.ssh/known_hosts
      #- run: ssh -4 -i id_rsa -nN -L 9000:172.31.58.162:9000 root@meltwatersecurityguild.cf &
      - run: bash -c "sudo ssh -4 -i id_rsa -NL 9000:172.31.58.162:9000 root@meltwatersecurityguild.cf &"
      #- run: sudo cat /my_log
      - run: sleep 30
      - run: wget -nv https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip
      - run: unzip -quo sonar-scanner-cli-3.0.3.778-linux.zip -d ../
      - run: sudo echo "sonar.host.url=http://localhost:9000" > ../sonar-scanner-3.0.3.778-linux/conf/sonar-scanner.properties
      - run: ../sonar-scanner-3.0.3.778-linux/bin/sonar-scanner -Dsonar.login=$SONAR_TOKEN
