machine:
  java:
  services:
dependencies:
  pre:
    - openssl aes-256-cbc -d -in circle_certbundle.enc.zip -out circle_certbundle.zip -k $Decrypt_var
    - unzip circle_certbundle.zip
    - sudo apt-get update && sudo apt-get install openvpn
    - sudo openvpn --config ovpnclient.conf --remap-usr1 SIGTERM --connect-retry-max 2 --single-session --log ./my.log
deployment:
  publish:
    branch: master
    commands:
    
